---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: vault_demo
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: vault_demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
      app.kubernetes.io/name: vault_demo
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
      labels:
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
        app.kubernetes.io/name: vault_demo
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: ACTIVE_PROFILE
                  name: cluster-config
            - name: VAULT_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: VAULT_ENABLED
                  name: cluster-config
            - name: VAULT_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: VAULT_BACKEND
                  name: cluster-config
            - name: VAULT_URL
              valueFrom:
                configMapKeyRef:
                  key: VAULT_URL
                  name: cluster-config
            - name: VAULT_KEY
              valueFrom:
                secretKeyRef:
                  key: VAULT_KEY
                  name: vault-springboot-secrate
            - name: VAULT_ROLE_ID
              valueFrom:
                configMapKeyRef:
                  key: VAULT_ROLE_ID
                  name: cluster-config
          image: ghcr.io/nikhil12894/vault_demo
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: vault_demo
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: vault_demo
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: vault_demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: vault_demo
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
